name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies for .NET 6
      run: dotnet restore

    - name: Build for .NET 6
      run: dotnet build --no-restore

    - name: Test for .NET 6
      run: dotnet test --no-build --verbosity normal

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies for .NET 8
      run: dotnet restore

    - name: Build for .NET 8
      run: dotnet build --no-restore
